name: auto-merge

on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
